### ISSUE TITLE
Determine our main objective and 8-12 questions

### ISSUE THREAD

**Issue by robbstenman** [robbstenman/Project_1_Poverty#4]
The Project 1 PDF says "Describe the purpose of your project and the problems you aim to solve." We aren't necessarily tying to solve a problem, but rather to gain an understanding of poverty in Colorado and how it impacts or is impacted by other factors.

**Comment by robbstenman** [comment]
As a group, we will figure out our hypothesis.

**Comment by Buford4** [comment]
1. Is there a correlation between poverty and housing?
2. Is there a correlation between poverty and education?
3. Is there a correlation between poverty and employment?
4. Is there a correlation between poverty and crime?
